version: '3.8'

services:
  web:
    build: .
    container_name: backend
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"


volumes:
  postgres_data:
