# Generated by Django 5.1.7 on 2025-03-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technical_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.CharField(max_length=100)),
                ('cargo_capacity', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('wheelbase', models.CharField(max_length=100)),
                ('wheel_formula', models.CharField(max_length=100)),
                ('engine_volume', models.CharField(max_length=100)),
                ('max_power', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('file', models.URLField()),
                ('technical_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.technical_specification')),
            ],
        ),
    ]
