# Generated by Django 4.2.20 on 2025-03-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_technical_specification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical_specification',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel'),
            preserve_default=False,
        ),
    ]
